#!/usr/bin/env node
const core=require('./core');
function output(value){console.log(JSON.stringify(value,null,2));}
async function main(){const [command,...args]=process.argv.slice(2);const asJson=args.includes('--json');if(command==='start'){const sep=args.indexOf('--');if(sep<1||sep===args.length-1)throw new Error('用法: project-services start <服务名> [--temporary] [--port auto|数字] [--json] -- <命令> [参数]');const flags=args.slice(1,sep);for(let i=0;i<flags.length;i++){if(['--port','--retries'].includes(flags[i])){i++;if(!flags[i])throw new Error('Missing option value');}else if(!['--json','--temporary'].includes(flags[i]))throw new Error(`Unknown option: ${flags[i]}`);}const value=flag=>{const index=flags.indexOf(flag);return index<0?undefined:flags[index+1];};const port=value('--port');if(port!==undefined&&port!=='auto'&&(!/^\d+$/.test(port)||Number(port)<1||Number(port)>65535))throw new Error('Port must be auto or 1..65535');const retries=value('--retries');if(retries!==undefined&&(!/^\d+$/.test(retries)||Number(retries)>100))throw new Error('Retries must be 0..100');const result=await core.startService({serviceName:args[0],command:args.slice(sep+1),temporary:flags.includes('--temporary'),asJson:flags.includes('--json'),port,retries:retries===undefined?3:Number(retries)});const {child,...record}=result;if(asJson)output(record);else console.log(`${record.service} ${record.action} (${record.status||'temporary'}) ${record.address||''}`);if(child){let finishing=false;const finish=async(code=0)=>{if(finishing)return;finishing=true;await core.cleanupTemporary(record.key,child);process.exitCode=code;};process.once('SIGINT',()=>finish(130));process.once('SIGTERM',()=>finish(143));child.once('exit',(code,signal)=>finish(code??(signal?1:0)));}return;}
if(command==='list'||command==='discover'){const items=await (command==='list'?core.listServices():core.discoverServices());if(asJson)output(items);else items.forEach(item=>console.log(`${item.workspace||'-'} ${item.service||item.command||'-'} ${item.status||'external'} ${item.pid||'-'} ${item.address||'-'}`));return;}
if(['stop','restart','delete','logs'].includes(command)){if(!args[0])throw new Error(`用法: project-services ${command} <服务名>`);const key=`${core.workspace()}::${args[0]}`;if(command==='logs')process.stdout.write(core.serviceLogs(key));else {const result=await core.actionService(key,command);if(asJson)output(result);else console.log(`${args[0]} ${command} complete`);}return;}
if(command==='associate'){if(!args[0]||!args[1])throw new Error('用法: project-services associate <pid> <workspace>');const result=await core.associateService(args[0],args[1]);asJson?output(result):console.log(`Associated ${result.pid} with ${result.workspace}`);return;}
if(command==='doctor'){const result=core.doctor();if(asJson)output(result);else result.checks.forEach(x=>console.log(`${x.ok?'ok':'fail'} ${x.name}: ${x.detail}`));if(!result.ok)process.exitCode=1;return;}
if(command==='dashboard'){const portIndex=args.indexOf('--port');const port=portIndex>=0?Number(args[portIndex+1]):0;if(!Number.isInteger(port)||port<0||port>65535)throw new Error('Port must be 0..65535');const dashboard=require('./dashboard');await dashboard.startDashboard({port});return;}
throw new Error('用法: project-services <start|list|discover|associate|stop|restart|delete|logs|doctor|dashboard>');}
main().catch(error=>{console.error(error.message);process.exitCode=1;});
