const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const crypto=require('node:crypto');
const {execFileSync,spawn}=require('node:child_process');
const ports=require('./ports');
const home=path.resolve(process.env.PORT_MANAGER_HOME||path.join(os.homedir(),'.project-services'));
const registryPath=path.join(home,'services.json');
const lockPath=path.join(home,'start.lock');
const pm2=process.env.PORT_MANAGER_PM2_BIN||require.resolve('pm2/bin/pm2');
const pmEnv={...process.env,PM2_HOME:path.join(home,'pm2')};
function call(args){return execFileSync(pm2,args,{env:pmEnv,encoding:'utf8',stdio:['ignore','pipe','pipe']});}
function processes(){return JSON.parse(call(['jlist','--silent']));}
function read(){try{return JSON.parse(fs.readFileSync(registryPath,'utf8'));}catch(e){if(e.code==='ENOENT')return {services:{}};throw e;}}
function write(reg){fs.mkdirSync(home,{recursive:true,mode:0o700});const temp=`${registryPath}.${process.pid}.tmp`;fs.writeFileSync(temp,JSON.stringify(reg,null,2)+'\n',{mode:0o600});fs.renameSync(temp,registryPath);}
function alive(pid){try{process.kill(pid,0);return true;}catch(e){return e.code==='EPERM';}}
async function lock(fn){fs.mkdirSync(home,{recursive:true,mode:0o700});const token=crypto.randomUUID();let acquired=false;for(let i=0;i<200;i++){try{fs.mkdirSync(lockPath);fs.writeFileSync(path.join(lockPath,'owner'),JSON.stringify({pid:process.pid,token}));acquired=true;break;}catch(e){if(e.code!=='EEXIST')throw e;try{const owner=JSON.parse(fs.readFileSync(path.join(lockPath,'owner'),'utf8'));if(Number.isInteger(owner.pid)&&!alive(owner.pid))fs.rmSync(lockPath,{recursive:true,force:true});}catch{}await new Promise(r=>setTimeout(r,50));}}if(!acquired)throw new Error('无法获取注册表锁，请稍后重试');try{return await fn();}finally{try{if(JSON.parse(fs.readFileSync(path.join(lockPath,'owner'),'utf8')).token===token)fs.rmSync(lockPath,{recursive:true,force:true});}catch{}}}
function workspace(cwd=process.cwd()){try{return fs.realpathSync(execFileSync('git',['rev-parse','--show-toplevel'],{cwd,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim());}catch{return fs.realpathSync(cwd);}}
function name(ws,service){return `project-services:${path.basename(ws).replace(/[^\w-]/g,'-')}:${crypto.createHash('sha256').update(JSON.stringify([ws,service])).digest('hex').slice(0,20)}`;}
async function enrich(entry,ps,all){const proc=ps.find(p=>p.name===entry.processName);const pid=entry.managed?proc?.pid:entry.pid;const family=ports.descendants(pid);const addresses=await Promise.all(all.filter(x=>family.has(x.pid)).map(ports.probe));return {...entry,pid:pid||null,status:entry.managed?(proc?.pm2_env?.status||'stopped'):(alive(pid)?'external':'stopped'),addresses,address:addresses.find(x=>x.verified)?.address||null};}
async function listServices(){const reg=read();let ps=[];try{ps=processes();}catch{}let all=[];try{all=ports.listeners();}catch{}return Promise.all(Object.values(reg.services).map(e=>enrich(e,ps,all)));}
async function discoverServices(){const registered=await listServices();return Promise.all(ports.listeners().map(async item=>({...await ports.probe(item),managed:false,workspace:registered.find(e=>ports.descendants(e.pid).has(item.pid))?.workspace||null,key:registered.find(e=>ports.descendants(e.pid).has(item.pid))?.key||null})));}
function launch(entry){fs.mkdirSync(home,{recursive:true,mode:0o700});const file=path.join(home,`${crypto.createHash('sha256').update(entry.key).digest('hex')}.launch.json`);const command=Array.isArray(entry.command)?entry.command:['/bin/sh','-c',entry.command];fs.writeFileSync(file,JSON.stringify({...entry,command}),{mode:0o600});call(['start',path.join(__dirname,'runner.js'),'--name',entry.processName,'--cwd',entry.cwd,'--time','--max-restarts',String(entry.retries??3),'--restart-delay','1000','--',file]);}
async function startService(options){return lock(async()=>{const ws=workspace();const key=`${ws}::${options.serviceName}`;const reg=read();const existing=(await listServices()).find(x=>x.key===key);if(existing&&['online','launching','temporary'].includes(existing.status))return {action:'existing',...existing};let port;if(options.port!==undefined)port=await ports.freePort(options.port==='auto'?0:Number(options.port));const entry={key,workspace:ws,cwd:process.cwd(),service:options.serviceName,processName:name(ws,options.serviceName),command:options.command,temporary:!!options.temporary,managed:true,startedAt:new Date().toISOString(),retries:options.retries??3,env:port?{PORT:String(port)}:{}};
if(entry.temporary){const child=spawn(entry.command[0],entry.command.slice(1),{cwd:entry.cwd,env:{...process.env,...entry.env},stdio:options.asJson?['inherit','ignore','inherit']:'inherit',detached:process.platform!=='win32'});await new Promise((resolve,reject)=>{child.once('spawn',resolve);child.once('error',reject);});entry.pid=child.pid;entry.managed=false;entry.status='temporary';reg.services[key]=entry;write(reg);return {action:'started',...entry,child};}
launch(entry);reg.services[key]=entry;write(reg);let result;for(let i=0;i<10;i++){result=(await listServices()).find(x=>x.key===key);if(result.address||!['online','launching'].includes(result.status))break;await new Promise(r=>setTimeout(r,100));}return {action:'started',...result};});}
async function actionService(key,action){if(!['stop','restart','delete'].includes(action))throw new Error('Unsupported action');return lock(async()=>{const reg=read();const entry=reg.services[key];if(!entry)throw new Error('当前工作区没有登记服务');if(!entry.managed)throw new Error('外部服务仅关联，不能接管或终止');let ps=processes();if(action==='restart'&&!ps.some(p=>p.name===entry.processName))launch(entry);else if(ps.some(p=>p.name===entry.processName))call([action,entry.processName]);if(action==='delete'){delete reg.services[key];write(reg);}return {action,key};});}
function serviceLogs(key){const entry=read().services[key];if(!entry)throw new Error('当前工作区没有登记服务');if(!entry.managed)throw new Error('外部服务没有托管日志');return call(['logs',entry.processName,'--nostream','--lines','50']);}
async function associateService(pid,ws){pid=Number(pid);if(!Number.isInteger(pid)||pid<=0||!ports.listeners().some(x=>x.pid===pid))throw new Error('PID 必须是当前监听进程');ws=workspace(path.resolve(ws));return lock(()=>{const reg=read();const key=`${ws}::external-${pid}`;const entry={key,workspace:ws,service:`external-${pid}`,pid,managed:false,temporary:false};reg.services[key]=entry;write(reg);return entry;});}
async function cleanupTemporary(key,child){try{process.kill(process.platform==='win32'?child.pid:-child.pid,'SIGTERM');}catch{}await lock(()=>{const reg=read();if(reg.services[key]?.pid===child.pid){delete reg.services[key];write(reg);}});}
function doctor(){const checks=[];const add=(name,fn)=>{try{checks.push({name,ok:true,detail:fn()});}catch(e){checks.push({name,ok:false,detail:e.message});}};add('node',()=>{if(Number(process.versions.node.split('.')[0])<24)throw new Error('Node >=24 required');return process.version;});add('pm2',()=>{call(['-v']);return pm2;});add('registry',()=>{fs.mkdirSync(home,{recursive:true,mode:0o700});fs.accessSync(home,fs.constants.R_OK|fs.constants.W_OK);return registryPath;});add('pm2-daemon',()=>{processes();return 'reachable';});return {ok:checks.every(x=>x.ok),checks};}
module.exports={listServices,discoverServices,actionService,serviceLogs,associateService,startService,cleanupTemporary,doctor,workspace,home,pmEnv};
